// Code generated by templ - DO NOT EDIT.

// templ: version: 0.2.476
package addworker

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "lps/pkg/templates/page"
import "lps/pkg/templates/form"
import "lps/internal/domain"

func formOpts(handler string) form.FormOpts {
	return form.FormOpts{
		Label:      "Add New Employee",
		Handler:    handler,
		Id:         "#new_employe__form",
		ButtonText: "Add",
	}
}

func loginOpts() form.TextFieldOpts {
	return form.TextFieldOpts{
		Label:       "Login:",
		Placeholder: "Enter the login...",
		Id:          "login",
		Name:        "login",
		Required:    true,
	}
}

func surnameOpts() form.TextFieldOpts {
	return form.TextFieldOpts{
		Label:       "Surname:",
		Placeholder: "Enter the surname...",
		Id:          "surname",
		Name:        "surname",
		Required:    true,
	}
}

func nameOpts() form.TextFieldOpts {
	return form.TextFieldOpts{
		Label:       "Name:",
		Placeholder: "Enter the name...",
		Id:          "name",
		Name:        "name",
		Required:    true,
	}
}

func patronymicOpts() form.TextFieldOpts {
	return form.TextFieldOpts{
		Label:       "Patronymic",
		Placeholder: "Enter the patronymic or leave empty...",
		Id:          "patronymic",
		Name:        "patronymic",
	}
}

func phoneOpts() form.TextFieldOpts {
	return form.TextFieldOpts{
		Label:    "Phone Number:",
		Type:     "tel",
		Id:       "phone_number",
		Name:     "phone_number",
		Required: true,
	}
}

func positionsOpts(positions []domain.Position) form.SelectorOpts {
	options := make([]form.OptionOpts, len(positions))
	for i, v := range positions {
		options[i] = form.OptionOpts{Name: v.Title, Value: v.ID.String()}
	}

	return form.SelectorOpts{
		Name:     "position",
		Label:    "Position:",
		HasEmpty: false,
		Options:  options,
	}
}

func departmentsOpts(departments []domain.Department) form.SelectorOpts {
	options := make([]form.OptionOpts, len(departments))
	for i, v := range departments {
		options[i] = form.OptionOpts{Name: v.Name, Value: v.ID.String()}
	}

	return form.SelectorOpts{
		Label:    "Department: ",
		Name:     "department",
		HasEmpty: false,
		Options:  options,
	}
}

func addWorkerPage(handler string, positions []domain.Position, departments []domain.Department) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
			if !templ_7745c5c3_IsBuffer {
				templ_7745c5c3_Buffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
			}
			templ_7745c5c3_Err = page.NavigationBar().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Var3 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
				templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
				if !templ_7745c5c3_IsBuffer {
					templ_7745c5c3_Buffer = templ.GetBuffer()
					defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
				}
				templ_7745c5c3_Err = form.TextField(loginOpts()).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = form.TextField(surnameOpts()).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = form.TextField(nameOpts()).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = form.TextField(patronymicOpts()).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = form.TextField(phoneOpts()).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = form.Selector(positionsOpts(positions)).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = form.Selector(departmentsOpts(departments)).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				if !templ_7745c5c3_IsBuffer {
					_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
				}
				return templ_7745c5c3_Err
			})
			templ_7745c5c3_Err = form.Form(formOpts(handler)).Render(templ.WithChildren(ctx, templ_7745c5c3_Var3), templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !templ_7745c5c3_IsBuffer {
				_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = page.Wrapper(page.Header("Add New Employee")).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
