#!/usr/bin/bash

# Since the Postgres currently unable to use ENV Variables inside .sql scripts.
# This file contains definitions user roles, values of which are taken from ENV variables

psql -U ${POSTGRES_USER} -d ${POSTGRES_DB} <<-END
    CREATE ROLE ${POSTGRES_ADMIN_NAME} WITH
    LOGIN
    PASSWORD '${POSTGRES_ADMIN_PWD}';

    GRANT ALL PRIVILEGES ON TABLE positions TO ${POSTGRES_ADMIN_NAME};
    GRANT ALL PRIVILEGES ON TABLE departments TO ${POSTGRES_ADMIN_NAME};
    GRANT ALL PRIVILEGES ON TABLE professional_developments TO ${POSTGRES_ADMIN_NAME};
    GRANT ALL PRIVILEGES ON TABLE incidents TO ${POSTGRES_ADMIN_NAME};
    GRANT ALL PRIVILEGES ON TABLE accounts TO ${POSTGRES_ADMIN_NAME};
    GRANT ALL PRIVILEGES ON TABLE staff TO ${POSTGRES_ADMIN_NAME};
    

    CREATE ROLE ${POSTGRES_HEAD_NAME} WITH
    LOGIN
    PASSWORD '${POSTGRES_HEAD_PWD}';

    GRANT SELECT, INSERT, UPDATE ON TABLE positions TO ${POSTGRES_HEAD_NAME};
    GRANT SELECT, UPDATE ON TABLE departments TO ${POSTGRES_HEAD_NAME};
    GRANT SELECT, INSERT, UPDATE ON TABLE professional_developments TO ${POSTGRES_HEAD_NAME};
    GRANT SELECT, UPDATE ON TABLE accounts TO ${POSTGRES_HEAD_NAME};
    GRANT ALL PRIVILEGES ON TABLE staff TO ${POSTGRES_HEAD_NAME};


    CREATE ROLE ${POSTGRES_STAFF_NAME} WITH
    LOGIN 
    PASSWORD '${POSTGRES_STAFF_PWD}';

    GRANT SELECT ON TABLE positions TO ${POSTGRES_STAFF_NAME};
    GRANT SELECT ON TABLE departments TO ${POSTGRES_STAFF_NAME};
    GRANT SELECT ON TABLE professional_developments TO ${POSTGRES_STAFF_NAME};
    GRANT SELECT, UPDATE ON TABLE accounts TO ${POSTGRES_STAFF_NAME};
    GRANT SELECT, INSERT, UPDATE ON TABLE incidents TO ${POSTGRES_STAFF_NAME};
END
